### PR TITLE
Bug Fix #40 generate X new devices in Region

### LINKED ISSUE #40: generate X new devices in <Region>
🐛 this work one time (not X=100) and stop.

### PR DESCRIPTION
**Pull request by boly38**
- Bug Fix #40 generate X new devices in Region
- fix lint warn for lo-device.js (esversion: 11, es2020 true..)

### CODE REVIEW

File: samples/lo-device/lo-device.js [hunk 1]
```diff
@@ -37,696 +40,642 @@ const topicResourceUpd = 'dev/rsc/upd';
...
 process.stdin.setRawMode(true);
 
-process.stdin.on('keypress', (function () {
-  return async (str, key) => {
-    if (key.name === 'q'
-        || (key && key.ctrl && key.name === 'c')) {
-      bye();
-      return;
+process.stdin.on('keypress', async (str, key) => {
+    if (key.name === 'q' || (key?.ctrl && key.name === 'c')) {
```
Comment (boly38) [inline samples/lo-device/lo-device.js:592]: jshint ne supporte pas l'optional chaining ?

Comment (boly38) [reply samples/lo-device/lo-device.js:592]: upd `.eslintrc` and `.jshintrc`

**Comment by boly38** [comment]
hound fixed by adding eslint [version](https://help.houndci.com/en/articles/2461415-supported-linters) 8.1.0 to `.hound.yml`
